return {
    ShotEffect = "Bullet",
    HitMarkEffect = "Smoke",
    FlashColor = Color3.fromRGB(255, 177, 42),
    HitMarkEffectConfig = {
        Color = ColorSequence.new(Color3.fromRGB(255, 170, 0), Color3.fromRGB(102, 48, 26)),
    },
    ShotEffectConfig = {
        Beam0 = { Color = ColorSequence.new(Color3.fromRGB(255, 170, 0)) },
        Beam1 = { Color = ColorSequence.new(Color3.fromRGB(255, 223, 39)) },
    },
}
